<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Copyright>Copyright © 2022</Copyright>
    <Version>1.1.0</Version>
    <Description>VIDAR toolkit test.</Description>
    <Authors>Pavel Zaytsev</Authors>
    <Company>Iberis Software</Company>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Api\x64\VToolkit.dll" Link="VToolkit.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BitMiracle.LibTiff.NET" Version="2.4.649" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VidarToolkit\VidarToolkit.csproj" />
  </ItemGroup>

</Project>
